### ISSUE TITLE
Opus files and sorting playlists

### ISSUE THREAD

**Issue by jaystermusic** [yoyofr/modizer#116]
Hello,

Opus files seem to be crashing the latest version of the app. Also, sorting playlists also seems to crash the app when there are many files in the playlist, and the songs all disappear from the playlist upon opening Modizer again. Version 3.3 fixed the issue with the songs disappearing (though the app still crashed), but the issue seems to be back with the newest release.

**Comment by yoyofr** [comment]
I'm not familiar with 'opus' file. Could you please share some examples (attached or a link) ?
For the playlist, how many entries to do have (roughly) ?

**Comment by jaystermusic** [comment]
It’s a lossy audio format; I believe it’s supported by VGMStream, so maybe the latest version is causing the issue. There are a couple of example files on this page. https://hydrogenaud.io/index.php/topic,122093.0.html

The playlists that are crashing Modizer are large; in excess of 8000 files.

**Comment by yoyofr** [comment]
ok, I found the issue / opus file. Will be fixed in v3.6, was linked to having wrong header files version for FFMpeg. Once using the uptodate one it's working well.
For the playlist I need to check, but 8000 is huge! :)

**Comment by yoyofr** [comment]
Playlist management is now much better in dev build (will be part of v3.6).
Testing with full HVSC and Asma (+60k entries) on iPhone SE and it is stable and fast so far.
Also added new features:
- sort playlist by full path
- save a playlist as a new one (to copy and then edit)
- now playing list is now saved as a gzip internal file instead of user preferences (to avoid limit of user preferences storage size)

**Comment by jaystermusic** [comment]
Perfect, thanks so much!

**Comment by yoyofr** [comment]
v3.6 released
