### ISSUE TITLE
3.5 feedback

### ISSUE THREAD

**Issue by Abster876** [yoyofr/modizer#118]
Hello.  I want to provide some feedback for the latest version, 3.5.

NSF infinite playback is still broken.  Whenever I turn the infinity switch on the current tune still fades away and ends after 10 minutes.  It also displays as a length of 10 minutes.  I’ll show a couple pictures to show what’s going on.

![BC6282C6-E1BC-49D5-A86F-63179327F3F3](https://github.com/yoyofr/modizer/assets/162279246/824a3dd7-29d5-4c2f-a020-87d006747f9c)
![AA5AA95F-754F-48FC-9F35-3D9F7420D510](https://github.com/yoyofr/modizer/assets/162279246/5ea2fa92-8296-456e-b926-2c00a7bca2b2)

.imf files (Commander Keen/Duke 2/Wolf 3d) have imperfect instruments no matter which settings I choose in ADPLUG.  Perhaps that music driver can use an update?

LIBKSS for MSX tracks has imperfect instruments as well.  This happened when the overhaul of MSX playback was implemented some versions back.  Perhaps the audio driver for MSX can be reverted back to a previous version?

**Comment by yoyofr** [comment]
Hi

Thanks for the detailed feedback.
V3.6 is almost ready, probably just a few days before I submit it to the
appstore for approval.

The nsf infinite playback / fade out issue will be fixed in it.

For imf file, 3.6 will feature a global upgrade of adplug, hopefully it
should fix the issue.

Regarding kss, I will try to update the libkss (need to check if a newer
version exists) and also add a switch in settings to select between libkss
and libgme (the old one).

Rgds
ym

**Comment by bri2000** [comment]
Hello, just installed v3.5 on my new phone, I'm finding a few bugs and I'm confused if the problem might be on my side. Modizer used to work perfect on my old iphone 11, using iphone 15 now.

If I use "add all to playlist", crash to desktop, if I use "add all to now playing" crash to desktop, if I try to add files to a new playlist, "add all" doesn't appear to do anything, "remove all" crashes to desktop.

Is 3.5 broken or is the problem at my side...?

Thank you!
- Brian

**Comment by yoyofr** [comment]
it looks like a bug. If I understand well, when you are in the file browser, you try to add the entries to a playlist by clicking on one of the 2 icons at the top (add to playlist or add to now playing). Is it correct ?
How many entries do you have ? Would be useful to have a few screenshots

**Comment by bri2000** [comment]
For example, fresh install. Library>Samples>Various. Only to midi files here. I press +ALL, app crashes. I press The headphones, "listen to all now", app crashes too. 

![IMG_1764](https://github.com/yoyofr/modizer/assets/162642893/1a47849c-bdc0-44a0-9e97-d0a84bf77b87)

A different bug, or problem I have. Playlists>select some playlist>add/remove files>samples>various. I press +ALL, nothing happens, they don't get added to playlist. I have to add one by one. I press -ALL, crash to desktop.

![IMG_1765](https://github.com/yoyofr/modizer/assets/162642893/afa8ca9b-4138-425f-9a42-9b51a316698e)

**Comment by yoyofr** [comment]
it's quite strange. Can you try reseting you settings "in more/maintenance". If still ko, you can try as well "clean database" and "recreate samples folder"

**Comment by bri2000** [comment]
It was a fresh install. I tried anyway, the 3 steps you mention, one by one. Crashed each time

**Comment by bri2000** [comment]
OK I found the problem. I downloaded the app in my wife's iphone 13, worked perfect as always. 

I found the problem was... text size. 

![IMG_1777](https://github.com/yoyofr/modizer/assets/162642893/f7fa9adb-0bcd-4deb-9abe-bb6bdbd0dbfc)

I have the text size in my phone too big. From this notch onwards, the app crashes. Just one notch to the left, modizer works fine. 

If you bother to fix it, it would be great 😄  For the time being, I'll just make a text in my phone a bit smaller.

Thank you for everything, I love modizer. Keep up the good work!

**Comment by yoyofr** [comment]
Ok, thanks for the update. I think I’ve identified the underlying issue, should be able to fix it for v3.6

**Comment by yoyofr** [comment]
Fixed in current dev build, will be part of v3.6

**Comment by bri2000** [comment]
Great!! Thank you!!
