### ISSUE TITLE
GSF Looping And Some GSF Problem

### ISSUE THREAD

**Issue by vus7294** [yoyofr/modizer#27]
1. All the GSF File (GBA CHIPTUNE) can't loop infinity. what's the problem?
2. Specific GSF File(example a link to the past on zophar) Can't Play. it has error mean "MISSING GSFLIB" But i can play SAME GSF FILE on highly advance 0.11 version. what's the problem?

**Comment by yoyofr** [comment]
1. If you activate the ‘infinite’ option (the horizontal 8), it should work -> one of the limit of the emulator used is that it cannot do ‘gapless’ infinite loop.
When reaching the end of the music, it will reload and restart (reset playback).
2. Thanks for pointing this, it will be fixed in v2.6 (gsflib path error when loading a music set based on nested gsflib files)
