### ISSUE TITLE
Modizer being unable to play FM instruments in S3M/MPTM modules

### ISSUE THREAD

**Issue by 0x5066** [yoyofr/modizer#46]
First off, I love this app, it is my go to for anything chiptune when I'm out.

One issue however is the lack of the player being unable to play S3M/MPTM files with OPL instruments (I assume this is due to libopenmpt not being updated to reflect this), which results in the instruments attempted to be played as samples, when they aren't, causing odd blips to be heard during playback

**Comment by yoyofr** [comment]
Hello, thanks for the feedback. I need to update libopenmpt, not sure what the latest can do.
For S3M Modizer can play adlib s3m file (s3m file using OPL instruments) if the extension is ".as3m" instead of ".s3m".
You can find some examples in online/modland, then choosing "format/..." and looking in the adlib/screamtracker 3 adlib folder

**Comment by yoyofr** [comment]
also you can rename a file by swiping on the right in the library view, choosing "rename" and changing the extension to .as3m (for s3m file, not for MPTM obviously :) )

**Comment by 0x5066** [comment]
Ah, my mistake then 😅
Had thought the OPL issue in mptm files was also present in S3M modules, but as3m modules are playing fine!

**Comment by yoyofr** [comment]
fixed in wip v2.9.6 (libopenmpt updated to latest version)
