### ISSUE TITLE
SIDs aren't infinite even with infinite mode enabled

### ISSUE THREAD

**Issue by 0x5066** [yoyofr/modizer#54]
As the title suggests, with infinite mode enabled, sidplayfp insists on still using the songlength provided from the HVSC instead of playing contineously like it did in versions prior, without infinite mode it behaves as it should

**Comment by yoyofr** [comment]
Hello, it is now fixed in the dev version, will be included in next release. Was related to trigerring a restart at the end of the 'theoritical' song end (songlength defined in HVSC database). I will let the file play infinitely when infinite mode is activated + add an option in the sidplayfp settings ('forceloop') to force a restart when the file is not looping by itself.
