### ISSUE TITLE
Oscilloscope problems

### ISSUE THREAD

**Issue by yaboinextd00r** [yoyofr/modizer#98]
Modizer has been my goto SID player for a long time and ive been enjoying it so far, I also enjoy watching oscilloscope views of sid music and watching those awesome waveforms!, one problem with the oscilloscope on Modizer, It kinda doesnt show filtered waveforms for some reason?. Switching from residfp to resid also causes sid files to not play properly.

Examples with Valleys of Europe by Linus:

Other Oscilloscope:
<img width="323" alt="oscilloscope1" src="https://user-images.githubusercontent.com/73263612/149332259-e9348faa-4b86-4936-8c52-3ddb84570d3a.PNG">

Modizer Oscilloscope:
![IMG_8162](https://user-images.githubusercontent.com/73263612/149332425-eac5b48d-6c9d-48bb-8926-d84b5503bb16.png)

Regards,

**Comment by 0x5066** [comment]
I would almost say that's a residfp feature as it looks like it's directly accessing the oscillators, since the view there doesn't look like it's run through the chip's highpass filter to remove any offset

Though the Oscilloscopes aren't clean looking either, since you can clearly see odd cuts in places, whereas in Oscilloscope programs with triggering functions, it's not there.

**Comment by yoyofr** [comment]
Hi, Modizer oscilloscope fx is not perfect and done in realtime. It cannot be as accurate as other softwares that usually requires to render each voice in a wav file and then compute the oscilloscope view/video.
